name:                generative
version:             0.1.0.0
github:              "githubuser/generative"
license:             None
author:              "Samuel GLogger"
maintainer:          "smorfi98@gmail.com"
copyright:           "2020 Samuel Glogger"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Library for computing generative art
category:            Art
description:         Please see the README on GitHub at <https://github.com/githubuser/generative#readme>

dependencies:
- base >= 4.7 && < 5
- repa

library:
  source-dirs: src

executables:
  generative-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -with-rtsopts=-N
    - -O2
    - -rtsopts
    - -threaded
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    - -fllvm
    - -optlo-O3
    dependencies:
    - generative

tests:
  generative-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generative
